// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TimeTracker.Data;

#nullable disable

namespace TimeTracker.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260804074920_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TimeTracker.Domain.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("color");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.ScheduleTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_schedule_templates");

                    b.ToTable("schedule_templates", (string)null);
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer")
                        .HasColumnName("schedule_id");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_sessions_schedule_id");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.SessionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_session_logs");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_session_logs_session_id");

                    b.ToTable("session_logs", (string)null);
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.TaskRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("ActualEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("actual_end");

                    b.Property<TimeOnly>("ActualStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("actual_start");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TaskInSessionId")
                        .HasColumnType("integer")
                        .HasColumnName("task_in_session_id");

                    b.HasKey("Id")
                        .HasName("pk_task_runs");

                    b.HasIndex("TaskInSessionId")
                        .HasDatabaseName("ix_task_runs_task_in_session_id");

                    b.ToTable("task_runs", (string)null);
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.TasksInGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("pk_tasks_in_groups");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_tasks_in_groups_group_id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_tasks_in_groups_task_id");

                    b.ToTable("tasks_in_groups", (string)null);
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.TasksInSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer")
                        .HasColumnName("schedule_id");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("pk_tasks_in_schedules");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_tasks_in_schedules_schedule_id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_tasks_in_schedules_task_id");

                    b.ToTable("tasks_in_schedules", (string)null);
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.TasksInSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("pk_tasks_in_sessions");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_tasks_in_sessions_session_id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_tasks_in_sessions_task_id");

                    b.ToTable("tasks_in_sessions", (string)null);
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.Session", b =>
                {
                    b.HasOne("TimeTracker.Domain.Entities.ScheduleTemplate", "Schedule")
                        .WithMany("Sessions")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_schedule_templates_schedule_id");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.SessionLog", b =>
                {
                    b.HasOne("TimeTracker.Domain.Entities.Session", "Session")
                        .WithMany("SessionLogs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_logs_sessions_session_id");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.TaskRun", b =>
                {
                    b.HasOne("TimeTracker.Domain.Entities.TasksInSession", "TasksInSession")
                        .WithMany("TaskRuns")
                        .HasForeignKey("TaskInSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_runs_tasks_in_sessions_task_in_session_id");

                    b.Navigation("TasksInSession");
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.TasksInGroup", b =>
                {
                    b.HasOne("TimeTracker.Domain.Entities.Group", "Group")
                        .WithMany("TasksInGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_in_groups_groups_group_id");

                    b.HasOne("TimeTracker.Domain.Entities.TaskItem", "Task")
                        .WithMany("TasksInGroups")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_in_groups_tasks_task_id");

                    b.Navigation("Group");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.TasksInSchedule", b =>
                {
                    b.HasOne("TimeTracker.Domain.Entities.ScheduleTemplate", "Schedule")
                        .WithMany("TasksInSchedules")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_in_schedules_schedule_templates_schedule_id");

                    b.HasOne("TimeTracker.Domain.Entities.TaskItem", "Task")
                        .WithMany("TasksInSchedules")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_in_schedules_tasks_task_id");

                    b.Navigation("Schedule");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.TasksInSession", b =>
                {
                    b.HasOne("TimeTracker.Domain.Entities.Session", "Session")
                        .WithMany("TasksInSessions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_in_sessions_sessions_session_id");

                    b.HasOne("TimeTracker.Domain.Entities.TaskItem", "Task")
                        .WithMany("TasksInSessions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_in_sessions_tasks_task_id");

                    b.Navigation("Session");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.Group", b =>
                {
                    b.Navigation("TasksInGroups");
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.ScheduleTemplate", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("TasksInSchedules");
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.Session", b =>
                {
                    b.Navigation("SessionLogs");

                    b.Navigation("TasksInSessions");
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.TaskItem", b =>
                {
                    b.Navigation("TasksInGroups");

                    b.Navigation("TasksInSchedules");

                    b.Navigation("TasksInSessions");
                });

            modelBuilder.Entity("TimeTracker.Domain.Entities.TasksInSession", b =>
                {
                    b.Navigation("TaskRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
